# Generated by Django 4.2 on 2023-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finaled_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('order_description', models.CharField(max_length=500, null=True)),
                ('total', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
