# Generated by Django 4.2 on 2023-12-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_finaled_order_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaled_order',
            name='total',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
