# Generated by Django 4.2 on 2023-12-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_finaled_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaled_order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=100, null=True),
        ),
    ]
