# Generated by Django 4.2 on 2023-12-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0002_medicine_digital_medicine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='digital',
        ),
    ]
